//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
fun main() {
    reto1ControlGastos()
    reto2FiltroEmpleados()
    reto3LimpiezaContactos()
    reto4CarritoCompras()
    reto5HistorialNavegacion()
    reto6CompatibilidadIntereses()
    reto7InventarioDespensa()
    reto8PromedioAcademico()
    reto9TraductorPaises()
    reto10RotacionTurnos()
    reto11OrganizadorMaleta()
    reto12RutaReversible()
    reto13RepartoPedidos()
    reto14TicketUnico()
    reto15IVASelectiva()
    reto16MantenimientoSensores()
    reto17MapaAlmacen()
    reto18FusionRecetas()
    reto19RankingApps()
    reto20UnionAgendas()
    reto21DiasPrimos()
    reto22PilaPlatos()
    reto23SeguimientoDieta()
    reto24ContenedoresBalanceados()
    reto25RendimientoMaraton()
    reto26CompresionLogs()
    reto27PremiosVendedores()
    reto28TarifasParking()
    reto29ParejasViajePeso()
    reto30EspejoLayout()
}